ItsDeltin/Overwatch-Script-To-Workshop

- Deltinteger/Deltinteger/Custom Methods/Array.cs
- Deltinteger/Deltinteger/Custom Methods/Destination.cs
- Deltinteger/Deltinteger/Custom Methods/EyeCastHitPosition.cs
- Deltinteger/Deltinteger/Custom Methods/FOVTakenUpBySphere.cs
- Deltinteger/Deltinteger/Custom Methods/HorizontalDistance.cs
- Deltinteger/Deltinteger/Custom Methods/IsOnScreen.cs
- Deltinteger/Deltinteger/Custom Methods/LinearInterpolate.cs
- Deltinteger/Deltinteger/Custom Methods/Midpoint.cs
- Deltinteger/Deltinteger/Custom Methods/Pythag.cs
- Deltinteger/Deltinteger/Custom Methods/README.md
- Deltinteger/Deltinteger/Custom Methods/SphereHitbox.cs
- Deltinteger/Deltinteger/Custom Methods/TallnessOfPlayer.cs
- Deltinteger/Deltinteger/Custom Methods/Units.cs
- Deltinteger/Deltinteger/Deltinteger.csproj
Adds a few Value methods converted from OSTW method library as well as the documentation added into the Custom Methods file. Not all have been tested but should hopefully all work.
Closes #39.
> Some custom methods

- Deltinteger/Deltinteger/Custom Methods/AngleOfVectors.cs
- Deltinteger/Deltinteger/Custom Methods/Array.cs
- Deltinteger/Deltinteger/Custom Methods/EyeCastHitPosition.cs
- Deltinteger/Deltinteger/Custom Methods/FOVTakenUpBySphere.cs
- Deltinteger/Deltinteger/Custom Methods/GetMap.cs
- Deltinteger/Deltinteger/Custom Methods/HorizontalDistance.cs
- Deltinteger/Deltinteger/Custom Methods/IsAI.cs
- Deltinteger/Deltinteger/Custom Methods/IsOnScreen.cs
- Deltinteger/Deltinteger/Custom Methods/LinearInterpolate.cs
- Deltinteger/Deltinteger/Custom Methods/Radians.cs
- Deltinteger/Deltinteger/Custom Methods/SetHealth.cs
- Deltinteger/Deltinteger/Custom Methods/SphereHitbox.cs
- Deltinteger/Deltinteger/Custom Methods/TallnessOfPlayer.cs
- Deltinteger/Deltinteger/Deltinteger.csproj
- Deltinteger/Deltinteger/Elements/Enums.cs
Added `ToDegrees`, `ToRadians`, `IsAIUnintrusive`, `IsAIAccurate` and `SetHealth`.
Added "Optimised" versions for many methods that use less server load but more variables and can not be used in conditions.
Added indications for all custom methods if they can not be used in a condition.
Closes #41.
> Some custom methods v2

- Deltinteger/Deltinteger/Custom Methods/AngleOfVectors.cs
- Deltinteger/Deltinteger/Custom Methods/Array.cs
- Deltinteger/Deltinteger/Custom Methods/FOVTakenUpBySphere.cs
- Deltinteger/Deltinteger/Custom Methods/LinearInterpolate.cs
- Deltinteger/Deltinteger/Custom Methods/Radians.cs
- Deltinteger/Deltinteger/Custom Methods/SetHealth.cs
- Deltinteger/Deltinteger/Custom Methods/TallnessOfPlayer.cs
- Deltinteger/Deltinteger/Custom Methods/Units.cs
- README.md
Updated README with new custom methods and features and added missing parameter descriptions for some custom methods.
> Documentation

- Deltinteger/Deltinteger/DeltinScript.g4
- Deltinteger/Deltinteger/Parse/Types/DefinedEnum.cs
> enums can be set to values instead of their IDs

- Deltinteger/Deltinteger/Parse/Expression.cs
> Throw error on usage of enums in ternaries

- Deltinteger/Deltinteger/Lobby/Ruleset.cs
Fix for Issue #172. Data Center Preference Select missing.
> Added a missing Lobby Setting (Data Center Preference) 

- Deltinteger/Deltinteger.sln
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- build: Bump Visual Studio version
- fix: Replace Cass' Flashbang with Magnetic Grenade in extension
> ow2 compatibility

- Deltinteger/Deltinteger/Elements.json
fixes:
```An exception was thrown while parsing.
System.TypeInitializationException: The type initializer for 'Deltin.Deltinteger.Elements.ElementList' threw an exception.
---> System.Collections.Generic.KeyNotFoundException: The enum member 'Visible To Position Direction and Size' was not found.
at Deltin.Deltinteger.Elements.ElementEnum.GetMemberFromWorkshop(String name) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Elements/Structure.cs:line 178
at Deltin.Deltinteger.Elements.ElementParameter.GetDefaultValue() in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Elements/Structure.cs:line 145
at Deltin.Deltinteger.Elements.ElementList..ctor(ElementBaseJson function) in …
```
> fix "Visible To Position Direction and Size" exception

- Deltinteger/Deltinteger/Elements.json
- Deltinteger/Deltinteger/Lobby/Modes.cs
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- feat: Add new Limit Roles option for "1 Tank, 2 Offense, 2 Support"
- fix: Include correct PlayEffect instead of duplicate
> small updates

- Deltinteger/Deltinteger/Lobby/Heroes.cs
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- overwatch-script-to-workshop/package-lock.json
- fix: Use new names for Ashe Coach Gun knockback settings
- feat: Add Doomfist Power Block Charge Rate setting
- fix: Update Illari to have Healing Dealt
- build: Update package-lock.json
Fixes #444 
Fixes #458
> season 6 settings fixes

- Deltinteger/Deltinteger/Lobby/Heroes.cs
- Deltinteger/Deltinteger/Program.cs
- Deltinteger/Deltinteger/publish.ps1
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- overwatch-script-to-workshop/package-lock.json
- overwatch-script-to-workshop/package.json
- feat: Add Sombra's new ability Virus
- chore: Bump langserver and extension versions
> add sombra rework

- Deltinteger/Deltinteger/Lobby/Heroes.cs
- Deltinteger/Deltinteger/Program.cs
- Deltinteger/Deltinteger/publish.ps1
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- overwatch-script-to-workshop/package-lock.json
- overwatch-script-to-workshop/package.json
Add Pig Pen and change Take a Breather to a resource-based ability.
> feat: Implement Roadhog rework

- Deltinteger/Deltinteger/Decompiler/TextToElement/EventInfo.cs
- Deltinteger/Deltinteger/Elements.json
- Deltinteger/Deltinteger/Elements/Enums.cs
- Deltinteger/Deltinteger/Lobby/Heroes.cs
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
This pull request adds support for the newest tank hero in Overwatch: Mauga﻿
> feat: add Mauga

- Deltinteger/Deltinteger/Lobby/Heroes.cs
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
This PR adds back the Take a Breather cooldown slider
> fix: add Take a Breather cooldown time

- Deltinteger/Deltinteger/Elements.json
> Correctly parse and emit vanilla player slot selector

- Deltinteger/Deltinteger/Lobby/Heroes.cs
> 481 bug decompile failing on mercy angelic descent off

- Deltinteger/Deltinteger/Elements.json
- Deltinteger/Deltinteger/Lobby/Heroes.cs
- Deltinteger/Deltinteger/LobbySettings.json
- Deltinteger/Deltinteger/Maps.json
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- **feat: add Runasapi**
- **feat: rename Cassidy's ability 2 from Magnetic Grenade to Flashbang**
> feat: season 11 parity

- Deltinteger/Deltinteger/Lobby/Heroes.cs
This PR adds the missing projectile gravity setting to Baptiste
> fix: add projectile gravity to Baptiste

- Deltinteger/Deltinteger/Parse/Parameters/AlternateParameterTypes.cs
Fixes #475
- **fix: allow expressions which resolve to a constant string to be considered valid for ConstStringParameter**
> 475 workshopsettingcombo and workshopsettinghero only accept string literals for category and name arguments

- Deltinteger/Deltinteger/Decompiler/TextToElement/EventInfo.cs
- Deltinteger/Deltinteger/Elements.json
- Deltinteger/Deltinteger/Elements/Enums.cs
- Deltinteger/Deltinteger/Lobby/Heroes.cs
- Deltinteger/Deltinteger/LobbySettings.json
This PR adds the new tank hero Hazard.
> feat: add hazard

- Deltinteger/Deltinteger/Lobby/Heroes.cs
- Deltinteger/Deltinteger/LobbySettings.json
This PR adds the passive health regeneration switch in the custom game settings.
> feat: add passive health regeneration setting

- Deltinteger/Deltinteger/Lobby/Modes.cs
- Deltinteger/Deltinteger/LobbySettings.json
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- **feat: add enable perks lobby setting**
> feat: enable perks lobby setting

- Deltinteger/Deltinteger/Elements.json
- Deltinteger/Deltinteger/Lobby/Heroes.cs
- Deltinteger/Deltinteger/LobbySettings.json
- Deltinteger/Deltinteger/Maps.json
- overwatch-script-to-workshop/json-schemas/LobbySettingValidation.json
- **feat: add freja**
- **feat: add Aatlis**
> feat: season 17
